logger:
  path: logs/date-update-scripts.log
  level: debug
  console: false
csv:
  path: /Users/bigfish/Documents/csv_data_path/
  oldAdPvClickCostDailyCsvFileName: old_ad_pv_click_cost_daily.csv
  oldCampaignDataDailySummariesCsvFileName: old_campaign_data_daily_summaries.csv
  oldCreativeDataDailySummariesCsvFileName: old_creative_data_daily_summaries.csv
  oldUserDataDailySummariesCsvFileName: old_user_data_daily_summaries.csv
  oldAllUsersDataDailySummariesCsvFileName: old_all_users_data_daily_summaries.csv
sql:
  path: /Users/bigfish/Documents/data_sql_file/
  adPvClickCostDailySqlFileName: ad_pv_click_cost_daily.sql
  campaignDataDailySummariesSqlFileName: campaign_data_daily_summaries.sql
  campaignDataSummariesSqlFileName: campaign_data_summaries.sql
  creativeDataDailySummariesSqlFileName: creative_data_daily_summaries.sql
  creativeDataSummariesSqlFileName: creative_data_summaries.sql
  userDataDailySummariesSqlFileName: user_data_daily_summaries.sql
  allUsersDataDailySummariesSqlFileName: all_users_data_daily_summaries.sql

